### ISSUE TITLE
cache should be gitignored

### ISSUE THREAD

**Issue by SuperCuber** [jakob-kruse/dotfiles#1]
Hey, first of all thanks for using Dotter :)

I wanted to note that `.dotter/cache.toml` should be gitignored, as you can see in my [own dotfiles](https://github.com/SuperCuber/dotfiles/blob/2b2887a92dfe04efaef133156d6570d1decf880f/.gitignore#L3-L5), and yyou probably want `local.toml` gitignored too.

Make sure you have git record them as removed when you add them to the gitignore because it doesn't happen automatically

**Comment by jakob-kruse** [comment]
Hey. Thanks for the heads up. I'm refactoring a bit at the moment, but I will keep that in mind!

Awesome tool btw :)
